# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'army.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2205, 664)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setAutoFillBackground(True)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(5, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.to_juke = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_juke.sizePolicy().hasHeightForWidth())
        self.to_juke.setSizePolicy(sizePolicy)
        self.to_juke.setMinimumSize(QtCore.QSize(100, 100))
        self.to_juke.setSizeIncrement(QtCore.QSize(100, 100))
        self.to_juke.setBaseSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.to_juke.setFont(font)
        self.to_juke.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-style: inset;\n"
"border-width: 3px;\n"
"border-color: #9c9c9c;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"border-style: inset;\n"
"background-color: #fff;\n"
"}")
        self.to_juke.setIconSize(QtCore.QSize(100, 100))
        self.to_juke.setCheckable(True)
        self.to_juke.setObjectName("to_juke")
        self.verticalLayout_7.addWidget(self.to_juke)
        self.to_objflw = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_objflw.sizePolicy().hasHeightForWidth())
        self.to_objflw.setSizePolicy(sizePolicy)
        self.to_objflw.setMinimumSize(QtCore.QSize(100, 100))
        self.to_objflw.setSizeIncrement(QtCore.QSize(100, 100))
        self.to_objflw.setBaseSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.to_objflw.setFont(font)
        self.to_objflw.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-style: inset;\n"
"border-width: 3px;\n"
"border-color: #9c9c9c;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"border-style: inset;\n"
"background-color: #fff;\n"
"}")
        self.to_objflw.setIconSize(QtCore.QSize(100, 100))
        self.to_objflw.setCheckable(True)
        self.to_objflw.setObjectName("to_objflw")
        self.verticalLayout_7.addWidget(self.to_objflw)
        self.to_gass = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_gass.sizePolicy().hasHeightForWidth())
        self.to_gass.setSizePolicy(sizePolicy)
        self.to_gass.setMinimumSize(QtCore.QSize(100, 100))
        self.to_gass.setSizeIncrement(QtCore.QSize(100, 100))
        self.to_gass.setBaseSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.to_gass.setFont(font)
        self.to_gass.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-style: inset;\n"
"border-width: 3px;\n"
"border-color: #9c9c9c;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"border-style: inset;\n"
"background-color: #fff;\n"
"}")
        self.to_gass.setIconSize(QtCore.QSize(100, 100))
        self.to_gass.setCheckable(True)
        self.to_gass.setChecked(False)
        self.to_gass.setAutoExclusive(False)
        self.to_gass.setDefault(False)
        self.to_gass.setFlat(False)
        self.to_gass.setObjectName("to_gass")
        self.verticalLayout_7.addWidget(self.to_gass)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.horizontalWidget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.horizontalWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QWidget(self.horizontalWidget)
        self.menu.setEnabled(True)
        self.menu.setObjectName("menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.logo.setFont(font)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.horizontalLayout.addWidget(self.menu)
        self.objflw = QtWidgets.QGroupBox(self.horizontalWidget)
        self.objflw.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objflw.sizePolicy().hasHeightForWidth())
        self.objflw.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setKerning(True)
        self.objflw.setFont(font)
        self.objflw.setAlignment(QtCore.Qt.AlignCenter)
        self.objflw.setFlat(False)
        self.objflw.setCheckable(False)
        self.objflw.setChecked(False)
        self.objflw.setObjectName("objflw")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.objflw)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.objflw_img = QtWidgets.QLabel(self.objflw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objflw_img.sizePolicy().hasHeightForWidth())
        self.objflw_img.setSizePolicy(sizePolicy)
        self.objflw_img.setText("")
        self.objflw_img.setAlignment(QtCore.Qt.AlignCenter)
        self.objflw_img.setObjectName("objflw_img")
        self.horizontalLayout_3.addWidget(self.objflw_img)
        self.objflw_sw = QtWidgets.QPushButton(self.objflw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objflw_sw.sizePolicy().hasHeightForWidth())
        self.objflw_sw.setSizePolicy(sizePolicy)
        self.objflw_sw.setMinimumSize(QtCore.QSize(100, 100))
        self.objflw_sw.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-style: inset;\n"
"border-width: 3px;\n"
"border-color: #9c9c9c;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"border-style: inset;\n"
"background-color: #fff;\n"
"}")
        self.objflw_sw.setText("")
        self.objflw_sw.setIconSize(QtCore.QSize(100, 100))
        self.objflw_sw.setCheckable(True)
        self.objflw_sw.setFlat(True)
        self.objflw_sw.setObjectName("objflw_sw")
        self.horizontalLayout_3.addWidget(self.objflw_sw)
        self.horizontalLayout.addWidget(self.objflw)
        self.jukebox = QtWidgets.QGroupBox(self.horizontalWidget)
        self.jukebox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jukebox.sizePolicy().hasHeightForWidth())
        self.jukebox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.jukebox.setFont(font)
        self.jukebox.setStyleSheet("")
        self.jukebox.setAlignment(QtCore.Qt.AlignCenter)
        self.jukebox.setFlat(False)
        self.jukebox.setObjectName("jukebox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.jukebox)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.juke_img = QtWidgets.QLabel(self.jukebox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juke_img.sizePolicy().hasHeightForWidth())
        self.juke_img.setSizePolicy(sizePolicy)
        self.juke_img.setText("")
        self.juke_img.setAlignment(QtCore.Qt.AlignCenter)
        self.juke_img.setObjectName("juke_img")
        self.verticalLayout_2.addWidget(self.juke_img)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.juke_title = QtWidgets.QLabel(self.jukebox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juke_title.sizePolicy().hasHeightForWidth())
        self.juke_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.juke_title.setFont(font)
        self.juke_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.juke_title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.juke_title.setLineWidth(1)
        self.juke_title.setText("")
        self.juke_title.setTextFormat(QtCore.Qt.AutoText)
        self.juke_title.setAlignment(QtCore.Qt.AlignCenter)
        self.juke_title.setOpenExternalLinks(False)
        self.juke_title.setObjectName("juke_title")
        self.verticalLayout_3.addWidget(self.juke_title)
        self.progressBar = QtWidgets.QProgressBar(self.jukebox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.juke_external = QtWidgets.QPushButton(self.jukebox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juke_external.sizePolicy().hasHeightForWidth())
        self.juke_external.setSizePolicy(sizePolicy)
        self.juke_external.setMinimumSize(QtCore.QSize(100, 100))
        self.juke_external.setSizeIncrement(QtCore.QSize(0, 0))
        self.juke_external.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 25px;\n"
"border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-style: inset;\n"
"border-width: 3px;\n"
"border-color: #9c9c9c;\n"
"}\n"
"\n"
"QPushButton:released{\n"
"border-style: inset;\n"
"border-width: 2px;\n"
"border-color: #9c9c9c;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"border-style: inset;\n"
"background-color: #fff;\n"
"}")
        self.juke_external.setIconSize(QtCore.QSize(100, 100))
        self.juke_external.setCheckable(True)
        self.juke_external.setObjectName("juke_external")
        self.horizontalLayout_2.addWidget(self.juke_external)
        self.juke_prev = QtWidgets.QPushButton(self.jukebox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juke_prev.sizePolicy().hasHeightForWidth())
        self.juke_prev.setSizePolicy(sizePolicy)
        self.juke_prev.setMinimumSize(QtCore.QSize(100, 100))
        self.juke_prev.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 25px;\n"
"border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-style: inset;\n"
"border-width: 3px;\n"
"border-color: #9c9c9c;\n"
"}")
        self.juke_prev.setIconSize(QtCore.QSize(100, 100))
        self.juke_prev.setFlat(False)
        self.juke_prev.setObjectName("juke_prev")
        self.horizontalLayout_2.addWidget(self.juke_prev)
        self.juke_play = QtWidgets.QPushButton(self.jukebox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juke_play.sizePolicy().hasHeightForWidth())
        self.juke_play.setSizePolicy(sizePolicy)
        self.juke_play.setMinimumSize(QtCore.QSize(100, 100))
        self.juke_play.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 25px;\n"
"border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-style: inset;\n"
"border-width: 3px;\n"
"border-color: #9c9c9c;\n"
"}")
        self.juke_play.setIconSize(QtCore.QSize(100, 100))
        self.juke_play.setCheckable(True)
        self.juke_play.setChecked(False)
        self.juke_play.setAutoDefault(False)
        self.juke_play.setDefault(False)
        self.juke_play.setFlat(False)
        self.juke_play.setObjectName("juke_play")
        self.horizontalLayout_2.addWidget(self.juke_play)
        self.juke_next = QtWidgets.QPushButton(self.jukebox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juke_next.sizePolicy().hasHeightForWidth())
        self.juke_next.setSizePolicy(sizePolicy)
        self.juke_next.setMinimumSize(QtCore.QSize(100, 100))
        self.juke_next.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 25px;\n"
"border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-style: inset;\n"
"border-width: 3px;\n"
"border-color: #9c9c9c;\n"
"}")
        self.juke_next.setIconSize(QtCore.QSize(100, 100))
        self.juke_next.setFlat(False)
        self.juke_next.setObjectName("juke_next")
        self.horizontalLayout_2.addWidget(self.juke_next)
        self.juke_volume = QtWidgets.QDial(self.jukebox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juke_volume.sizePolicy().hasHeightForWidth())
        self.juke_volume.setSizePolicy(sizePolicy)
        self.juke_volume.setMinimumSize(QtCore.QSize(200, 200))
        self.juke_volume.setMaximum(100)
        self.juke_volume.setSliderPosition(50)
        self.juke_volume.setTracking(False)
        self.juke_volume.setOrientation(QtCore.Qt.Horizontal)
        self.juke_volume.setInvertedAppearance(False)
        self.juke_volume.setInvertedControls(False)
        self.juke_volume.setWrapping(False)
        self.juke_volume.setNotchTarget(10.0)
        self.juke_volume.setNotchesVisible(True)
        self.juke_volume.setObjectName("juke_volume")
        self.horizontalLayout_2.addWidget(self.juke_volume)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.jukebox)
        self.gass = QtWidgets.QGroupBox(self.horizontalWidget)
        self.gass.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gass.sizePolicy().hasHeightForWidth())
        self.gass.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.gass.setFont(font)
        self.gass.setAlignment(QtCore.Qt.AlignCenter)
        self.gass.setObjectName("gass")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gass)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gass_call = QtWidgets.QPushButton(self.gass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gass_call.sizePolicy().hasHeightForWidth())
        self.gass_call.setSizePolicy(sizePolicy)
        self.gass_call.setMinimumSize(QtCore.QSize(100, 100))
        self.gass_call.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 25px;\n"
"border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-style: inset;\n"
"border-width: 3px;\n"
"border-color: #9c9c9c;\n"
"}")
        self.gass_call.setText("")
        self.gass_call.setIconSize(QtCore.QSize(100, 100))
        self.gass_call.setObjectName("gass_call")
        self.horizontalLayout_5.addWidget(self.gass_call)
        self.gass_img = QtWidgets.QLabel(self.gass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gass_img.sizePolicy().hasHeightForWidth())
        self.gass_img.setSizePolicy(sizePolicy)
        self.gass_img.setMinimumSize(QtCore.QSize(0, 0))
        self.gass_img.setText("")
        self.gass_img.setAlignment(QtCore.Qt.AlignCenter)
        self.gass_img.setObjectName("gass_img")
        self.horizontalLayout_5.addWidget(self.gass_img)
        self.gass_snowboy = QtWidgets.QPushButton(self.gass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gass_snowboy.sizePolicy().hasHeightForWidth())
        self.gass_snowboy.setSizePolicy(sizePolicy)
        self.gass_snowboy.setMinimumSize(QtCore.QSize(100, 100))
        self.gass_snowboy.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 25px;\n"
"border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-style: inset;\n"
"border-width: 3px;\n"
"border-color: #9c9c9c;\n"
"}\n"
"\n"
"QPushButton:released{\n"
"border-style: inset;\n"
"border-width: 2px;\n"
"border-color: #9c9c9c;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"border-style: inset;\n"
"background-color: #fff;\n"
"}")
        self.gass_snowboy.setText("")
        self.gass_snowboy.setIconSize(QtCore.QSize(100, 100))
        self.gass_snowboy.setCheckable(True)
        self.gass_snowboy.setChecked(True)
        self.gass_snowboy.setObjectName("gass_snowboy")
        self.horizontalLayout_5.addWidget(self.gass_snowboy)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gass_text = QtWidgets.QTextEdit(self.gass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gass_text.sizePolicy().hasHeightForWidth())
        self.gass_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setKerning(False)
        self.gass_text.setFont(font)
        self.gass_text.setMouseTracking(False)
        self.gass_text.setAcceptDrops(False)
        self.gass_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gass_text.setAutoFillBackground(False)
        self.gass_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gass_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gass_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gass_text.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.gass_text.setDocumentTitle("")
        self.gass_text.setUndoRedoEnabled(False)
        self.gass_text.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.gass_text.setLineWrapColumnOrWidth(0)
        self.gass_text.setReadOnly(True)
        self.gass_text.setOverwriteMode(False)
        self.gass_text.setTabStopWidth(80)
        self.gass_text.setAcceptRichText(False)
        self.gass_text.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.gass_text.setObjectName("gass_text")
        self.horizontalLayout_4.addWidget(self.gass_text)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.gass)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.horizontalWidget, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Demo"))
        self.to_juke.setText(_translate("Form", "JukeBox"))
        self.to_objflw.setText(_translate("Form", "Follow \n"
"a person"))
        self.to_gass.setText(_translate("Form", "Voice\n"
"Assistant"))
        self.logo.setText(_translate("Form", "Loading..."))
        self.objflw.setTitle(_translate("Form", "Follow a person"))
        self.jukebox.setTitle(_translate("Form", "JukeBox"))
        self.juke_external.setText(_translate("Form", "External"))
        self.juke_prev.setText(_translate("Form", "Previous"))
        self.juke_play.setText(_translate("Form", "Play"))
        self.juke_next.setText(_translate("Form", "Next"))
        self.gass.setTitle(_translate("Form", "Voice Assistant"))
        self.gass_text.setPlaceholderText(_translate("Form", "Sentences recognized as voice are displayed here."))
